definitions:
  response.UserGet:
    properties:
      nickName:
        type: string
    type: object
info:
  contact: {}
paths:
  /user:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserGet'
        "500":
          description: Something wrong
          schema:
            type: string
      summary: 認証情報から自分のユーザー情報を取得する
swagger: "2.0"
