version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./build/app/Dockerfile
    command: /company-official-app-backend
    env_file: 
      - ./envs/.env
    ports:
      - 8080:8080
  db:
    image: mysql:8.0
    command: mysqld
    volumes:
        - ./build/db/my.cnf:/etc/mysql/conf.d/my.cnf
        - db-data:/var/lib/mysql
    env_file:
        - ./envs/.env
    ports:
        - 3306:3306
volumes:
  db-data: