version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./build/app/Dockerfile
    command: /company-official-app-backend
    env_file: 
      - ./config/.env
    ports:
      - "8080:8080"