definitions:
  controller.userCreateReq:
    properties:
      nickname:
        type: string
    required:
    - nickname
    type: object
info:
  contact: {}
paths:
  /user:
    get:
      consumes:
      - application/json
      parameters:
      - description: Authentiation header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Something wrong
          schema:
            type: string
        "404":
          description: Something wrong
          schema:
            type: string
        "500":
          description: Something wrong
          schema:
            type: string
      summary: 認証情報から自分のユーザー情報を取得する
    post:
      consumes:
      - application/json
      parameters:
      - description: Authentiation header
        in: header
        name: Authorization
        required: true
        type: string
      - description: request body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/controller.userCreateReq'
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "500":
          description: Something wrong
          schema:
            type: string
      summary: 認証情報とリクエスト情報からユーザーを作成する
swagger: "2.0"
