// Code generated by MockGen. DO NOT EDIT.
// Source: domain/operator/app.go

// Package mock_operator is a generated GoMock package.
package mock_operator

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/ishihaya/company-official-app-backend/domain/entity"
)

// MockAppID is a mock of AppID interface.
type MockAppID struct {
	ctrl     *gomock.Controller
	recorder *MockAppIDMockRecorder
}

// MockAppIDMockRecorder is the mock recorder for MockAppID.
type MockAppIDMockRecorder struct {
	mock *MockAppID
}

// NewMockAppID creates a new mock instance.
func NewMockAppID(ctrl *gomock.Controller) *MockAppID {
	mock := &MockAppID{ctrl: ctrl}
	mock.recorder = &MockAppIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppID) EXPECT() *MockAppIDMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockAppID) Generate(t time.Time) (entity.AppID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", t)
	ret0, _ := ret[0].(entity.AppID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockAppIDMockRecorder) Generate(t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockAppID)(nil).Generate), t)
}
