package router

import (
	"fmt"
	"log"

	// docs is generated by Swag CLI, you have to import it.
	_ "github.com/ishihaya/company-official-app-backend/docs/swagger"

	"github.com/gin-gonic/gin"
	"github.com/ishihaya/company-official-app-backend/config"
	"github.com/ishihaya/company-official-app-backend/di"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

type Router struct {
	*gin.Engine
}

// New - ルーティング関数の生成
func New() *Router {
	engine := gin.Default()
	gin.SetMode(gin.ReleaseMode)
	return &Router{Engine: engine}
}

// Routes - ルーティングを制御する関数
func (r *Router) Routes() {
	userHandler := di.InitUser()

	r.GET("/user", userHandler.Get)
}

// LoadSwagger - Swaggerを読み込む関数
func (r *Router) LoadSwagger() {
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
}

// RunServer - サーバーを走らせる関数
func (r *Router) RunServer() {
	if err := r.Run(fmt.Sprintf(":%s", config.PORT())); err != nil {
		log.Fatal(err)
	}
}
