name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_READ_WRITE_KEY }}
jobs:
  build_and_push:
    name: Build and push
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ env.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-company-official-app-backend-image-${{ github.sha }}
          restore-keys: ${{ runner.os }}-docker-company-official-app-backend-image-
      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker --quiet
      - name: Build and push image
        uses: docker/build-push-action@v2
        env:
          IMAGE: asia.gcr.io/${{ env.GCP_PROJECT_ID }}/company-official-app-backend:${{ github.sha }}
        with:
          context: .
          file: build/app/Dockerfile
          push: true
          target: deploy
          tags: ${{ env.IMAGE }}
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build_and_push
    environment:
      name: dev
    defaults:
      run:
        working-directory: ./terraform/envs/dev
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ env.GCP_SA_KEY }}
          export_default_credentials: true
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      - name: Init
        run: terraform init -input=false
      - name: Validate
        run: terraform validate
      - name: Apply
        run: terraform apply -input=false -auto-approve
